### PR TITLE
Additional IISFTP server support and Download callback

### PR DESCRIPTION
**Pull request by Rokke**
Download callback for progress
IISFTP support where full year is not returned in LIST

### CODE REVIEW

**Comment by salim-lachdhaf** [comment]
You are not well formatting the code
https://github.com/salim-lachdhaf/ftpConnect/runs/1520326252?check_suite_focus=true

**Comment by Rokke** [comment]
Working on it :)
Never used dartfmt and new to this kind of Git so I have to investigate some time regarding this.
I also put back the DIR_LIST_COMMAND and enum TransferMode with adding the exports in ftpconnect.dart instead

**Comment by salim-lachdhaf** [comment]
No , it's not export issue, revert that.

You have made change in dir_list_command...
And forget to update unit tests importation.
I'm helping you to get used with this things ;)

**Comment by Rokke** [comment]
But the test went ok when running them locally
And my vscode is reformatting the files wrong so will start to use android studio until I figure out how to set up vscode correctly

**Comment by Rokke** [comment]
I'm sorry that I'm commiting so many times and probably doing this so wrong but I'm new to this
I should probably have started with the dev branch and then commiting that to the master branch before trying to pull to your repo?

**Comment by salim-lachdhaf** [comment]
There is something wrong with file download, the file is not getting written ;)

**Comment by salim-lachdhaf** [comment]
No problem, take your time and test as you want

**Comment by Rokke** [comment]
My host application are working fine and downloading the file.
Also why isn't it failing when running the test in Android Studio?

**Comment by salim-lachdhaf** [comment]
This is weired, try the pull request on master branch once

**Comment by Rokke** [comment]
Same result

**Comment by salim-lachdhaf** [comment]
You have something wrong ! I tested for a two commit on dev and master and it works fine.

I will check for your code tomorrow if you did not solve it.

**Comment by Rokke** [comment]
Thanks for help, I will also take the night

**Comment by Rokke** [comment]
Did this mean you was able to merge the code. Did you have to change something in the code?

**Comment by salim-lachdhaf** [comment]
i can from the start to merge your code even with existent issues, just i wanted to give you the time to test and learn ..., however , i merged it to make things more faster and made some other changes, for example the on progress contains errors (data.lenght gives just the current received data not the sum) and add some extra features like progress in percent ...
the same thing will be added in the upload process ;)

**Comment by Rokke** [comment]
Thanks I also thought about that but I allready know the total size of the file before the download so that was not something I needed. I also figured out when I started to play with your code that you was checking the filesize before download but then I had already implemented the filesize in the host application.
But do you know what kind of issues there was that stopped the merge?

**Comment by Rokke** [comment]
Wouldn't it be better to have the progress value as actual bytes sent so that it's possible to receive the correct amount of bytes (and calculate the percent self if needed)? You are also sending the full length each time so then I would say it's better to have the current downloaded and full length instead. If you want to show bytes downloaded so far you would have to use the percentage * fullsize and then round this(and still not correct)

**Comment by salim-lachdhaf** [comment]
i'm not sending the full length, i'm sending the accumulated (up/down-loawded) data, and the percentage, so he can know the total lenght of waited file. and prevent make thing more complicated for the user by calculating the percentage on our side.

**Comment by salim-lachdhaf** [comment]
> Wouldn't it be better to have the progress value as actual bytes sent so that it's possible to receive the correct amount of bytes (and calculate the percent self if needed)? You are also sending the full length each time so then I would say it's better to have the current downloaded and full length instead. If you want to show bytes downloaded so far you would have to use the percentage * fullsize and then round this(and still not correct)

if you want to get each time the received data , it's simple either, you can declare 
```
var x = lastTotalReceivedData; //should be a global variable , outside your onProgress FN
var y= currentTotalReicevedData;
var currentData = currentTotalReicevedData - lastTotalReceivedData;
x = currentTotalReicevedData;
```

**Comment by Rokke** [comment]
Sorry I was a bit quick there(didn't look inside the code) so I just thought that totalLength was the total size of the file and not the actuall downloaded value.
It wasn't the total data received that was a problem for me and I allread before starting the download check the filesize(so for me the implementation is just fine).
But I still think that instead of sending percentage and downloaded amount it would be usable for more ppl to have the total size of the file and the downloaded size. Then you would be able to cover all scenarios.
Let's say for instance now if you just want to use DownloadFile() and you don't know the filesize you could cover all scenarios with only sending currently downloaded bytes and the total filesize (maxvalue).
Then if you want just the most probable value (the percentage) you could just use x/y.
But in the scenario you want to show the actuall byte count and the total filesize you wouldn't be able to do this now.
You could ofcourse do a getFilesize first but this could also have changed before you start the download.
Calculate the total filesize of the file based on the percentage and the currently downloaded bytes would not be correct since it will round it. Then if the user see that the filesize is a total of 99999bytes and the user know that the file actually is 100000bytes that would probably not be good.
This is not a problem for me either way since I do a LIST directory before I start the download so I allready know the filesize and most probably the file wouldn't have changed before I start the download.

**Comment by salim-lachdhaf** [comment]
Yes , that's right, i will think about that in the next version, because i will add the same feature for folder downloads.

**Comment by Rokke** [comment]
So I don't do anything stupid (again)
Should I delete this fork now since I have added your dev branch as my master for my project?

**Comment by salim-lachdhaf** [comment]
As you want :) thank you for the idea of onProgess

**Pull request merged**
